name: .NET Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore Bank/Bank.WebApi/Bank.WebApi.csproj

    - name: Run unit tests
      run: dotnet test Bank/Bank.WebApi/Bank.WebApi.csproj --logger "trx" --results-directory ./TestResults

    # 🔧 Paso importante: SonarCloud análisis
    - name: SonarCloud Analysis
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=apibankk_lab2
          -Dsonar.organization=apibankk
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build NuGet Package
      run: dotnet pack Bank/Bank.WebApi/Bank.WebApi.csproj -o ./nupkgs

    - name: Publish NuGet Package to GitHub Packages
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/mayrafc/index.json" \
          --name github \
          --username mayrafc \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text

        dotnet nuget push ./nupkgs/*.nupkg --source "github"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
