name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  docfx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install DocFX locally
        run: |
          dotnet tool install docfx --version 2.59.4 --tool-path ./tools
          echo "$(pwd)/tools" >> $GITHUB_PATH

      - name: Build documentation
        run: |
          docfx metadata docfx.json
          docfx build docfx.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
