name: Release Version

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Bank/Bank.WebApi/Bank.WebApi.csproj

    - name: Run Unit Tests
      run: dotnet test Bank/Bank.WebApi.Tests/Bank.WebApi.Tests.csproj --no-restore --verbosity normal


    - name: Build NuGet Package
      run: dotnet pack Bank/Bank.WebApi/Bank.WebApi.csproj -o ./nupkgs

    - name: Verify .nupkg file
      run: |
        if ls ./nupkgs/*.nupkg 1> /dev/null 2>&1; then
          echo ".nupkg file found!"
        else
          echo "No .nupkg file found, aborting release step!"
          exit 1
        fi

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Create GitHub Release
      run: |
        RELEASE_TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
        echo "Creating release for tag: $RELEASE_TAG"
        gh release create $RELEASE_TAG ./nupkgs/*.nupkg --title "Release $RELEASE_TAG" --notes "Automated release for version $RELEASE_TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Upload .nupkg to GitHub Releases
      run: |
        RELEASE_TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
        gh release upload $RELEASE_TAG ./nupkgs/*.nupkg --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
